name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: mypkg
      - uses: ros-tooling/setup-ros@v0.3
      - run: |
          rosinstall_generator <package-name> --rosdistro <target-distro> \
          --deps-only --deps --upstream-development > /tmp/deps.repos
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: my_package
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/deps.repos

      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: ogi-y/color_msgs
          path: color_msgs
        
      - uses: ros-tooling/setup-ros@v0.3
      - run: |
          rosinstall_generator <package-name> --rosdistro <target-distro> \
          --deps-only --deps --upstream-development > /tmp/deps.repos
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: my_package
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/deps.repos

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Check directory
        run: |
          ls -l
          
      - run: |
          rsync -av ./ /root/ros2_ws/src/
          cd /root/ros2_ws
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y 
          echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
          echo "source ~/ros2_ws/install/setup.bash" >> ~/.bashrc
          echo "source ~/ros2_ws/install/local_setup.bash" >> ~/.bashrc
          ros2 pkg install ament_cmake
          colcon build
          bash -xv ./src/mypkg/test/test.bash /root
