name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Checkout
        working-directory: /root/ros2_ws/src/
        uses: actions/checkout@v3
        with:
          path: mypkg
      - name: Checkout another repo
      working-directory: /root/ros2_ws/src/
        uses: actions/checkout@v3
        with:
          repository: ogi-y/color_msgs
          path: color_msgs
      
      - name: Check directory
        run: |
          ls -l
          cd src
          ls -l
          
      - run: |
          ls -l
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          rosdep update
          rosdep install ament_cmake
          rosdep install -i --from-path src --rosdistro humble -y
          bash -xv ./src/mypkg/mypkg/test/test.bash /root
